// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";
import Teams from "./Teams";

export const components = {
  article: dynamic(() => import("./Article")),
  call_to_action: dynamic(() => import("./CallToAction")),
  cam_groundstation: dynamic(() => import("./CamGroundstation")),
  carousel: dynamic(() => import("./Carousel")),
  hero: dynamic(() => import("./Hero")),
  info_grid: dynamic(() => import("./InfoGrid")),
  info_header: dynamic(() => import("./InfoHeader")),
  membership_form: dynamic(() => import("./MembershipForm")),
  menu_item: dynamic(() => import("./MenuItem")),
  projects: dynamic(() => import("./Projects")),
  showcase: dynamic(() => import("./Showcase")),
  sponsors: dynamic(() => import("./Sponsors")),
  sub_menu_item: dynamic(() => import("./SubMenuItem")),
  subsections: dynamic(() => import("./Subsections")),
  team_members: dynamic(() => import("./TeamMembers")),
  testemonials: dynamic(() => import("./Testemonials")),
  teams: dynamic(() => import("./Teams")),
};
